// src/components/layout/Footer.tsx
import { Link } from "react-router-dom";
import {
  Instagram,
  Youtube,
  Facebook,
  MessageCircle,
  MapPin,
} from "lucide-react";
import Logo from "./Logo";

const Footer = () => {
  return (
    <footer className="bg-qc-black text-white">
      {/* Gold separator */}
      <div className="h-px bg-qc-gold" />

      <div className="max-w-7xl mx-auto px-6 lg:px-8 py-16">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-12">
          {/* Brand Column */}
          <div className="flex flex-col gap-5">
            <Logo size="default" />
            <p className="text-white/60 text-sm font-body leading-relaxed max-w-xs">
              A full-service creative and media brand where God-given visions
              become impactful realities. Spirit-inspired. Excellence-driven.
            </p>
            <div className="flex items-center gap-1 text-white/40 text-xs font-body">
              <MapPin size={12} />
              <span>Nigeria — Serving Clients Worldwide</span>
            </div>
          </div>

          {/* Quick Links */}
          <div>
            <h4 className="font-display text-lg tracking-widest text-qc-gold mb-6">
              QUICK LINKS
            </h4>
            <ul className="flex flex-col gap-3">
              {[
                { label: "Home", path: "/" },
                { label: "Services", path: "/services" },
                { label: "About Us", path: "/about" },
                { label: "Contact", path: "/contact" },
              ].map((link) => (
                <li key={link.path}>
                  <Link
                    to={link.path}
                    className="text-white/60 text-sm font-body hover:text-qc-gold transition-colors duration-200 flex items-center gap-2 group"
                  >
                    <span className="w-4 h-px bg-qc-gold/30 group-hover:bg-qc-gold group-hover:w-6 transition-all duration-200" />
                    {link.label}
                  </Link>
                </li>
              ))}
            </ul>
          </div>

          {/* Social + Contact */}
          <div>
            <h4 className="font-display text-lg tracking-widest text-qc-gold mb-6">
              CONNECT WITH US
            </h4>
            <div className="flex flex-col gap-4 mb-6">
              <a
                href="https://wa.me/234000000000"
                target="_blank"
                rel="noopener noreferrer"
                className="flex items-center gap-3 px-4 py-3 bg-[#25D366]/10 border border-[#25D366]/30 rounded-xl text-sm font-body text-white hover:bg-[#25D366]/20 transition-all duration-200"
              >
                <MessageCircle size={16} className="text-[#25D366]" />
                <span>Chat on WhatsApp</span>
              </a>
            </div>
            <div className="flex items-center gap-4">
              {[
                { icon: Instagram, label: "Instagram", href: "#" },
                { icon: Youtube, label: "YouTube", href: "#" },
                { icon: Facebook, label: "Facebook", href: "#" },
              ].map(({ icon: Icon, label, href }) => (
                <a
                  key={label}
                  href={href}
                  target="_blank"
                  rel="noopener noreferrer"
                  aria-label={label}
                  className="w-10 h-10 rounded-full border border-white/20 flex items-center justify-center text-white/60 hover:text-qc-gold hover:border-qc-gold transition-all duration-200"
                >
                  <Icon size={16} />
                </a>
              ))}
            </div>
          </div>
        </div>

        {/* Bottom bar */}
        <div className="mt-12 pt-8 border-t border-white/10 flex flex-col md:flex-row items-center justify-between gap-4">
          <p className="text-white/40 text-xs font-body">
            © 2025 Quickened Creations — Pneuma Inspired. All rights reserved.
          </p>
          <p className="text-white/20 text-xs font-body tracking-widest">
            SPIRIT · INSPIRED · EXCELLENCE
          </p>
        </div>
      </div>
    </footer>
  );
};

export default Footer;

// src/lib/components/footer.svelte
<!-- Footer -->
<footer class="w-full bg-zinc-100 px-12 py-20" id="contact">
	<div class="mx-auto grid max-w-screen-2xl grid-cols-1 items-start gap-10 md:grid-cols-3">
		<div>
			<span class="text-zinc-800 mb-6 block font-serif text-xl italic"> Quickened Creations</span>
			<p class="max-w-xl leading-relaxed text-zinc-700">
				A premium creative agency dedicated to high end video editing, music production,and modern
				digital experiences.
			</p>
		</div>
		<div class="flex flex-col gap-4">
			<h6 class="font-label mb-4 text-sm tracking-widest text-zinc-900 uppercase">Connect</h6>
			<!-- instagram link -->
			<a
				class="text-zinc-600 transition-all duration-500 hover:translate-x-1 hover:text-[#ffd700]"
				aria-label="Instagram Profile"
				href="https://instagram.com/quickenedcreations/"
				target="_blank">Instagram</a
			>
			<!--  linkedin link -->
			<a
				class="text-zinc-600 transition-all duration-500 hover:translate-x-1 hover:text-[#ffd700]"
				aria-label="linkedIn profile"
				href="https://linkedin.com/quickend-creation"
				target="_blank">LinkedIn</a
			>
			<!-- whatsapp link -->
			<a
				class="text-zinc-600 transition-all duration-500 hover:translate-x-1 hover:text-[#ffd700]"
				aria-label="Chat on WhatsApp"
				href="https://wa.me/+2348054501976"
				target="_blank">WhatsApp</a
			>
		</div>
	</div>
	<div
		class="mx-auto flex max-w-screen-2xl flex-col items-center justify-between gap-6 pt-12 md:flex-row"
	>
		<p class="font-label text-sm tracking-widest text-zinc-600 uppercase">
			&copy; 2026 Quickened Creations - Pneuma Inspired.
		</p>
	</div>
</footer>
